#!/bin/bash
#
# Converts a folder of FLAC files to ALAC files with ffmpeg

NQDIR="/tmp/flac-to-alac"
LOG_FILE="$HOME/Library/Logs/flac-to-alac/info.log"

log() {
    echo "[$(date "+%Y.%m.%d %H:%M:%S")] $1" >> $LOG_FILE 2>&1
}

usage() { 
    echo "Usage: ./flac-to-alac -i infolder -o outfolder"
}

while getopts hi:o: flag; do
    case "${flag}" in
        i) input="${OPTARG}" ;;
        o) output="${OPTARG}" ;;
        h) usage; exit ;;
    esac
done

if [ -z ${input+x} ] || [ -z ${output+x} ]; then
    echo "Must specify input and output folders"
    usage
    exit 1
fi

convert() {
    mkdir -p "$(dirname "$DEST_FILE")"

    if [ -s "$DEST_FILE" ]; then
        echo "Skipping existing file: $DEST_FILE"
        return 0
    fi

    if [ -e "$DEST_FILE" ]; then
        rm -f "$DEST_FILE"
    fi

    ffmpeg \
	-nostdin \
    -y \
    -i "$SOURCE_FILE" \
	-c:v copy \
	-c:a alac \
	-movflags +faststart \
    "$DEST_FILE"
}

typeset -fx convert

queue() {
    log "Converting $1"

    rel_path="${1#"$input"/}"
    if [ "$rel_path" = "$1" ]; then
        rel_path=$(basename "$1")
    fi

    dest_file="$output/${rel_path%.flac}.m4a"
    SOURCE_FILE="$1" DEST_FILE="$dest_file" NQDIR=$NQDIR nq -q bash -c 'convert'
}

mkdir -p "$(dirname "$LOG_FILE")"
mkdir -p "$NQDIR"

log "Checking path: $input"

find "$input" -name '*.flac' -print0 | 
while IFS= read -r -d '' line; do
    queue "$line"
done
